apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submariner-k8s-broker-cluster-secrets
  namespace: submariner-broker
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submariner-k8s-broker-cluster-secrets-local-cluster
  namespace: submariner-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-k8s-broker-cluster-secrets
subjects:
  - kind: ServiceAccount
    name: local-cluster
    namespace: submariner-broker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submariner-k8s-broker-cluster-secrets-cluster-two
  namespace: submariner-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-k8s-broker-cluster-secrets
subjects:
  - kind: ServiceAccount
    name: cluster-two
    namespace: submariner-broker
