---
# Secret for streaming replication user
# This user will be used by the replica cluster to connect
apiVersion: v1
kind: Secret
metadata:
  name: streaming-replica-secret
  namespace: cnpg-database
type: kubernetes.io/basic-auth
stringData:
  username: streaming-replica
  password: replicapassword123


